---
- name: Install ISC DHCP for Debian / Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - isc-dhcp-server
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - installation-debian
