---
- name: Copy dhcpd.conf to master
  ansible.builtin.template:
    src: dhcpd.conf.master.j2
    dest: /etc/dhcp/dhcpd.conf
    force: true
    owner: root
    group: root
    mode: '0644'
  when: "'master' in group_names"
  notify:
    - restart isc-dhcp-server

- name: Copy dhcpd.conf to slave
  ansible.builtin.template:
    src: dhcpd.conf.slave.j2
    dest: /etc/dhcp/dhcpd.conf
    force: true
    owner: root
    group: root
    mode: '0644'
  when: "'slave' in group_names"
  notify:
    - restart isc-dhcp-server

- name: Copy isc-dhcp-server
  ansible.builtin.template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    force: true
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart isc-dhcp-server

- name: Start and enable ISC DHCP
  ansible.builtin.systemd:
    enabled: true
    name: isc-dhcp-server
    state: started
  tags:
    - systemd-service
